language: node_js
node_js: '4.6'
install:
  - npm i -g gulp
branches:
  only:
  - master
before_script:
  - chmod 600 .travis/deploy-key
  - mv .travis/deploy-key ~/.ssh/id_rsa
  - git clone https://github.com/RocketChat/Rocket.Chat.Docs.Generator.git /tmp/generator
script:
  - export SRC_DIR=`pwd`
  - cd /tmp/generator
  - ln -s $SRC_DIR src
  - npm i
  - gulp build
after_success:
  - cd /tmp/generator
  - tar -czf package.tgz build
  - scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh
before_install:
  - echo -e "Host $DEPLOY_HOST\n\tHostName $DEPLOY_HOST\n\tStrictHostKeyChecking no\n\tUser github\n\tIdentityFile ~/.ssh/id_rsa\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_0da79f095df9_key -iv $encrypted_0da79f095df9_iv -in .travis/deploy-key.enc -out .travis/deploy-key -d
